//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("app.Domain.Resources.CustomMessages", typeof(CustomMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário autenticado..
        /// </summary>
        public static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleção.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar um usuário, é obrigatório informar a descrição..
        /// </summary>
        public static string DescriptionIsRequiredToCreatePermission {
            get {
                return ResourceManager.GetString("DescriptionIsRequiredToCreatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada está incorreta..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar um usuário, é obrigatório informar o login..
        /// </summary>
        public static string LoginIsRequiredToCreateUser {
            get {
                return ResourceManager.GetString("LoginIsRequiredToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para efetuar o login na aplicação, é necessário informar o login do usuário..
        /// </summary>
        public static string LoginIsRequiredToLogin {
            get {
                return ResourceManager.GetString("LoginIsRequiredToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar uma permissão, é obrigatório informar o nome..
        /// </summary>
        public static string NameIsRequiredToCreatePermission {
            get {
                return ResourceManager.GetString("NameIsRequiredToCreatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha {0}: Para criar um permissão,  é obrigatório informar o nome..
        /// </summary>
        public static string NameIsRequiredToCreatePermissionExcel {
            get {
                return ResourceManager.GetString("NameIsRequiredToCreatePermissionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar um perfil, é obrigatório informar o nome..
        /// </summary>
        public static string NameIsRequiredToCreateProfile {
            get {
                return ResourceManager.GetString("NameIsRequiredToCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar um usuário, é obrigatório informar o nome..
        /// </summary>
        public static string NameIsRequiredToCreateUser {
            get {
                return ResourceManager.GetString("NameIsRequiredToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para alterar a senha do usuário, é obrigatório informar a nova senha..
        /// </summary>
        public static string NewPasswordIsRequiredToChangeUserPassword {
            get {
                return ResourceManager.GetString("NewPasswordIsRequiredToChangeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de autenticação. Login ou senha inválidos..
        /// </summary>
        public static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para alterar a senha do usuário, é obrigatório informar a antiga senha..
        /// </summary>
        public static string OldPasswordIsRequiredToChangeUserPassword {
            get {
                return ResourceManager.GetString("OldPasswordIsRequiredToChangeUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar um usuário, é obrigatório informar a senha..
        /// </summary>
        public static string PasswordIsRequiredToCreateUser {
            get {
                return ResourceManager.GetString("PasswordIsRequiredToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para efetuar o login na aplicação, é necessário informar a senha do usuário..
        /// </summary>
        public static string PasswordIsRequiredToLogin {
            get {
                return ResourceManager.GetString("PasswordIsRequiredToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome {0} já é utilizado por uma permissão do sistema..
        /// </summary>
        public static string PermissionAlreadyExists {
            get {
                return ResourceManager.GetString("PermissionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo da descrição da permissão é 200..
        /// </summary>
        public static string PermissionDescriptionMaxLength {
            get {
                return ResourceManager.GetString("PermissionDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha {0}: O tamanho máximo da descrição da permissão é 200..
        /// </summary>
        public static string PermissionDescriptionMaxLengthExcel {
            get {
                return ResourceManager.GetString("PermissionDescriptionMaxLengthExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta permissão não existe no sistema..
        /// </summary>
        public static string PermissionIdNotExists {
            get {
                return ResourceManager.GetString("PermissionIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do nome da permissão é 50..
        /// </summary>
        public static string PermissionNameMaxLength {
            get {
                return ResourceManager.GetString("PermissionNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha {0}: O tamanho máximo do nome da permissão é 50..
        /// </summary>
        public static string PermissionNameMaxLengthExcel {
            get {
                return ResourceManager.GetString("PermissionNameMaxLengthExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome {0} já é utilizado por um perfil do sistema..
        /// </summary>
        public static string ProfileAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este perfil não pode ser deletado, pois é utilizado por um usuário..
        /// </summary>
        public static string ProfileCantBeDeleted {
            get {
                return ResourceManager.GetString("ProfileCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este perfil não existe no sistema..
        /// </summary>
        public static string ProfileIdNotExists {
            get {
                return ResourceManager.GetString("ProfileIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar/editar um usuário, é obrigatório informar o perfil..
        /// </summary>
        public static string ProfileIsRequiredToCreateUser {
            get {
                return ResourceManager.GetString("ProfileIsRequiredToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do nome do perfil é 50..
        /// </summary>
        public static string ProfileNameMaxLength {
            get {
                return ResourceManager.GetString("ProfileNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilha de Permissões.
        /// </summary>
        public static string SheetNameExcelPermission {
            get {
                return ResourceManager.GetString("SheetNameExcelPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilha de Importação de Permissões.
        /// </summary>
        public static string SheetNameImportExcelPermission {
            get {
                return ResourceManager.GetString("SheetNameImportExcelPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido a inserção de caracteres do tipo texto na coluna {0} da linha {1}.
        /// </summary>
        public static string StringNotAllowed {
            get {
                return ResourceManager.GetString("StringNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilha de Importação de Permissões.
        /// </summary>
        public static string TitleExcelImportPermission {
            get {
                return ResourceManager.GetString("TitleExcelImportPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O login {0} já é utilizado por um usuário do sistema..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuário não existe no sistema..
        /// </summary>
        public static string UserIdNotExists {
            get {
                return ResourceManager.GetString("UserIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do login do usuário é 20..
        /// </summary>
        public static string UserLoginMaxLength {
            get {
                return ResourceManager.GetString("UserLoginMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do nome do usuário é 100..
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário {0} não existe no sistema..
        /// </summary>
        public static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
    }
}
